version: "3"
services:
    client:
        container_name: client_side
        expose:  
          - ${REACT_APP_PORT}
        build:
          context: ./client
          dockerfile: Dockerfile
        environment: 
          - REACT_APP_PORT=${REACT_APP_PORT}
        image: pauromeropau/awesome_web
        ports:
          - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
          - ./client:/usr/src/app
        stdin_open: true
    server:
        container_name: server_side
        expose: 
          - ${APP_SERVER_PORT}
        build:
          context: ./server
          dockerfile: Dockerfile
        environment: 
          API_HOST: ${API_HOST} 
          API_SERVER_PORT: ${APP_SERVER_PORT}
        image: pauromeropau/awesome_server
        ports:
          - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
          - ./server:/usr/src/app
        stdin_open: true