version: "3"
services:
    client:
        container_name: client_side
        expose:  
          - ${REACT_APP_PORT}
        build:
          context: ./client
          dockerfile: Dockerfile
        environment: 
          - REACT_APP_PORT=${REACT_APP_PORT}
        image: pauromeropau/client
        ports:
          - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
          - ./client/src:/srv/app/phone-docker-client/src
          - ./client/public:/srv/app/phone-docker-client/public
        stdin_open: true
    server:
        container_name: server_side
        expose: 
          - ${APP_SERVER_PORT}
        build:
          context: ./server
          dockerfile: Dockerfile
        environment: 
          API_HOST: ${API_HOST} 
          API_SERVER_PORT: ${APP_SERVER_PORT}
        image: pauromeropau/server
        ports:
          - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
          - ./server/routes:/srv/app/phone-docker-server
        stdin_open: true