version: "3"
services:
    client:
        container_name: client_side
        build:
            context: ./client
            dockerfile: Dockerfile
        image: pauromeropau/awesome_web
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
        stdin_open: true
    server:
        container_name: server_side
        build:
            context: ./server
            dockerfile: Dockerfile
        image: pauromeropau/awesome_server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
        stdin_open: true