version : '3'

services:

  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST} 
      API_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
      - ./server/routes:/srv/app/guidesmith/routes
    command: 
      npm start
  client: 
    build: ./client
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose: 
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
      - ./client/src:/srv/app/guidesmith/src
      - ./client/public:/srv/app/guidesmith/public
    command: 
      npm start